In [2]:
### Impotring important libraies.
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
### Sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am good boy',
      'I am good developer',
      'undestand the meaning of word',
      'our videos are good']

In [8]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am good boy',
 'I am good developer',
 'undestand the meaning of word',
 'our videos are good']

In [9]:
## Vocabulary size=
voc_size=10000

### One Hot Representation

In [10]:
onehot_rep=[one_hot(words,voc_size)for words in sent]
print(onehot_rep)

[[9293, 6709, 8056, 6876], [9293, 6709, 8056, 8163], [9293, 4576, 8056, 2878], [5911, 2401, 7334, 454], [5911, 2401, 7334, 3515], [7173, 9293, 4623, 8056, 2101], [5051, 8224, 9161, 7334]]


### Word Embedding Representation

In [16]:
### Impotring important libraries.
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [20]:
sent_length=8
embedded_doc=pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)
print(embedded_doc)

[[   0    0    0    0 9293 6709 8056 6876]
 [   0    0    0    0 9293 6709 8056 8163]
 [   0    0    0    0 9293 4576 8056 2878]
 [   0    0    0    0 5911 2401 7334  454]
 [   0    0    0    0 5911 2401 7334 3515]
 [   0    0    0 7173 9293 4623 8056 2101]
 [   0    0    0    0 5051 8224 9161 7334]]


In [22]:
## Creating Dimention
dim=10

In [23]:
## creating the Sequential model.
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [25]:
model.predict(embedded_doc)

array([[[ 0.03142509,  0.0481419 , -0.03756101, -0.04353439,
          0.04241485,  0.02955582,  0.01989006,  0.04010374,
          0.03334013,  0.00876949],
        [ 0.03142509,  0.0481419 , -0.03756101, -0.04353439,
          0.04241485,  0.02955582,  0.01989006,  0.04010374,
          0.03334013,  0.00876949],
        [ 0.03142509,  0.0481419 , -0.03756101, -0.04353439,
          0.04241485,  0.02955582,  0.01989006,  0.04010374,
          0.03334013,  0.00876949],
        [ 0.03142509,  0.0481419 , -0.03756101, -0.04353439,
          0.04241485,  0.02955582,  0.01989006,  0.04010374,
          0.03334013,  0.00876949],
        [ 0.0193115 ,  0.03095916,  0.01342306, -0.04715973,
         -0.01200583, -0.01155356, -0.005064  ,  0.00823309,
         -0.00919705, -0.01715855],
        [-0.04525703, -0.03916434, -0.01987045,  0.02800772,
         -0.04057984,  0.01985489, -0.03562643,  0.04234275,
         -0.04631538,  0.00053344],
        [ 0.00160895, -0.00336004,  0.01563473, -0.0